### ISSUE TITLE
Feature parity with cancerinfocus.org (Use kentucky as an example) 

### ISSUE THREAD

**Issue by seandavi** [colorado-cancer-center/COCancerScope#1]
Here is a screenshot of the site. It is simple, but it is probably not a bad place to start.

![image](https://github.com/colorado-cancer-center/COCancerScope/assets/92435/0d06e7e4-ef54-4805-8b35-e680360b0ebd)

**Comment by vincerubinetti** [comment]
I'd say with the current features, and the addition this morning of the markers (#19 ), this is basically done. All that's left for the site to be "presentable" as an MVP is filling out some static content like the about page.
