### ISSUE TITLE
Fill out static content/text

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/COCancerScope#11]
About page, bottom of home page, etc. 

Also any links in the footer?

@janolowery

**Comment by janolowery** [comment]
text below.  Can we change the 'Markers' tab on site to 'Resources' to match text?

CU Cancer Center’s **E**xploring **C**ancer in **Co**lorado (ECCO)

ECCO is an interactive data resource that allows users to explore Colorado with respect to the demographics of our population, cancer burden, risk factors, and cancer disparities. It also contains data on health behaviors, environmental exposures and resources for cancer prevention, screening, treatment, and survivorship.  

Create your own map by selecting a geographic area and specific measure of interest.  You can view data at the county and census level (for some measures).  Clicking on a county or tract will reveal data specific to that geographic area.  You can also add one or more resources, which represent providers and other services, on top of your map.   Data can be downloaded in the form of an excel file, that can be used to generate tables and graphs.
