### ISSUE TITLE
Add overlays (markers, regions, etc) to map

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/COCancerScope#13]
cancerinfocus.org lets you select markers, regions, etc (let's call them "overlays) for things like lung cancer screening centers, toxic waste sites, food deserts, etc. These can be either exact points, or regions/areas (though they're generally smaller than countries/tracts).

Which of these sources of info do we want to add, and where would we get the data? I imagine this is something where we could add things to our hearts content based on what we find publicly available.

Sean had mentioned [this link](https://mcc-cri.shinyapps.io/cif-data/_w_2047ceba/session/f030b106800928482c155a0ff2e24bf5/download/dus?w=2047ceba), but this seems to not provide what I'd need to display on a map. We'd need some kind of geo coordinates, along with any other info on a per point basis (e.g. cancerinfocus.org shows facility hours and phone number when you click on a cancer screening center marker).

**Comment by seandavi** [comment]
In the data download from cancerinfocus, there is a file named `us_facilities_and_providers_05-20-2023`. As far as I can tell, ALL the data for cancerinfocus is in that download. 

D select * from 'us_facilities_and_providers_05-20-2023.parquet' using sample 10;
|               type               |                     name                     |                                   address                                   | state | phone_number |              notes              |  latitude   |   longitude   |  fips   |
|----------------------------------|----------------------------------------------|-----------------------------------------------------------------------------|-------|--------------|---------------------------------|-------------|---------------|---------|
| Obstetrics & Gynecology          | New Beginnings Obstetrics & Gynceology, P.C  | 1401 S Don Roser Dr, Suite D, Las Cruces, NM 88011                          | NM    | 575-522-2800 |                                 |             |               |         |
| FQHC                             | Daughters of Charity Health Center - Algiers | 3215 General Meyer Ave, New Orleans, LA 70114-3204                          | LA    | 504-362-8930 | All Other Clinic Types          | 29.94001229 | -90.02145955  |         |
| FQHC                             | Adelante Healthcare Peoria                   | 15525 N 83rd Ave, Ste 104, Peoria, AZ 85382-5820                            | AZ    | 877-809-5092 | All Other Clinic Types          | 33.62563889 | -112.23737231 |         |
| Superfund Site                   | BASIN TAILINGS                               | NO SPECIFIC ADDRESS, BASIN, MT 59631                                        | MT    |              | Site is Part of NPL Site        |             |               | 30043.0 |
| Obstetrics & Gynecology          | Isaac Kligman M.D.                           | 1305 York Ave, 6Th Floor, New York, NY 10021                                | NY    | 646-962-3814 |                                 |             |               |         |
| Mammography                      | Touchstone Imaging Wheat Ridge               | 7615 West 38th Avenue, Wheat Ridge, CO 80033                                | CO    | 7206833005   |                                 |             |               |         |
| Colon & Rectal Surgeon           | Bryan Cross D.O.                             | 2495 Shreveport Hwy (Va Medical Center), Mail Code 112, Pineville, LA 71360 | LA    | 318-466-4034 |                                 |             |               |         |
| Gastroenterology                 | Steve T Chen M.D.                            | 2112 Harrisburg Pike, Ste 202, Lancaster, PA 17601                          | PA    | 717-544-3500 |                                 |             |               |         |
| FQHC                             | Stephen Klein Wellness Center                | 2144 Cecil B Moore Ave, Philadelphia, PA 19121-4014                         | PA    | 215-320-6187 | All Other Clinic Types          | 39.98025598 | -75.17023813  |         |
| Toxic Release Inventory Facility | THETFORD CORP                                | 7101 Jackson Rd, Ann Arbor, MI 48103                                        | MI    |              | Chemicals relased: Formaldehyde | 42.291667   | -83.87        |         |

**Comment by BORRAYOE** [comment]
@vincerubinetti in reponse to your comment: "Sean had mentioned [this link](https://mcc-cri.shinyapps.io/cif-data/_w_2047ceba/session/f030b106800928482c155a0ff2e24bf5/download/dus?w=2047ceba), but this seems to not provide what I'd need to display on a map. We'd need some kind of geo coordinates, along with any other info on a per point basis.." We have a database with that information that is displayed on the map. However, it is our database and not publicly available (except for the display on the map). We can share that with you to display but not sure the best way to get that data to you?

**Comment by vincerubinetti** [comment]
From #15:

> Add cancer centers, etc. into overlays with comprehensive data (address, hours, etc.)

From #17:

> The map shows screening sites for "lung cancer screening" across cancers (e.g., female breast cancer). Is it possible to add the "other cancer screening sites" (e.g., Women Wellness Connection for Breast and Cervical Cancer) in our Website. https://medschool.cuanschutz.edu/colorado-cancer-center/community/CommunityOutreachEngagement/Colorado-Cancer-map
