### ISSUE TITLE
Meeting notes from 10/17/23

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/COCancerScope#15]
- [ ] Say where sources came from. Defer to CancerInFocus's sources page rather than duplicating data.
- [ ] Specify timespans over which rates are calculated.
- [ ] Nice to have absolute counts along with % rates (fix: AAC column in dataset?)
- [ ] Add cancer centers, etc. into overlays with comprehensive data (address, hours, etc.)
- [ ] Radon data?
- [ ] Investigate bug where downloading data produces empty sheet.
- [ ] Add support instructions for non-technical audience

**Comment by BORRAYOE** [comment]
@vincerubinetti I just responded to the item: "Add cancer centers, etc. into overlays with comprehensive data (address, hours, etc.)" That is available currently at our website.

**Comment by vincerubinetti** [comment]
I created this issue, but it's generally best to split issues up into specific, concrete tasks, rather than a list of unrelated things from a meeting. Usually you'd only do a list of small things in a single issue like this if you were intending to knock them all out in a single PR (pull request, a change to the code).

So, I've split these out into their own separate issues. Now, an issue can contain a discussion specific to just that task, and a PR can close a specific issue.
