### ISSUE TITLE
"Sources" page content

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/COCancerScope#20]
Split from #15

Say where sources came from. Defer to CancerInFocus's sources page rather than duplicating data.

**Comment by vincerubinetti** [comment]
We're going to have a dedicated Sources page, accessible from the header of the site, and populated with static text and citation data about each source, including timespans (per #21 ), linking to external info pages when possible/appropriate.

A shortened label or id or some citation for the source will be hardcoded into the backend for now and displayed on the frontend in the legend.

**Comment by vincerubinetti** [comment]
From Sean:

> Perhaps start as a google doc to keep list of where things come from and provide user-level and technical documentation.

**Comment by falquaddoomi** [comment]
From the meeting:

@vincerubinetti : would be good to have a meeting where we interactively put this together.

**Comment by vincerubinetti** [comment]
Merging in #21 

Also specify timespans of data.

> I believe the CancerInFocus data is from the last 2-5 years or something like that? Might be best to defer external pages for that info? Maybe linking to the appropriate documentation that says the timespans is enough...?

**Comment by cydneyj303** [comment]
Hi all -

Attached is a document with our data sources page. There is one highlighted part that we need your team's eyes for. If the highlighted part remains true then we can keep it in and can publish to the platform. If it is not true, we can delete or edit and publish. 

Thanks!
[DATA SOURCES_Final.docx](https://github.com/colorado-cancer-center/COCancerScope/files/14363930/DATA.SOURCES_Final.docx)
