### ISSUE TITLE
Need human-readable labels for CU cancer center marker data

### ISSUE THREAD

**Issue by vincerubinetti** [colorado-cancer-center/COCancerScope#26]
- wwc-15-jun-2021
- ccsp-15-jun-2021
- title-x-15-jun-2021
- chc-15-jun-2021
- rhc-15-jun-2021
- ihs-15-jun-2021
- genetic-coun-15-jun-2021
- all-treatment-15-jun-2021
- med-onc-15-jun-2021
- surg-onc-15-jun-2021
- rad-onc-15-jun-2021
- ped-onc-15-jun-2021
- trials-15-jun-2021
- all-support-services-15-jun-2021
- pt-rehab-15-jun-2021
- nutrition-15-jun-2021
- support-grp-15-jun-2021
- support-coun-15-jun-2021
- survivorship-15-jun-2021
- lodging-15-jun-2021
- financial-coun-15-jun-2021
- palliative-15-jun-2021
- hospice-15-jun-2021
- cancer-ed-29-jul-221
- accessories-aids-29-jul-21
- programs-events-29-jul-21
- fitness-29-jul-21
- home-family-care-29-jul-21
- transportation-29-jul-21
- pediatric-29-jul-21
- radiology

Also split this up into 3 to 5 (?) high level categories and multi-selects.

**Comment by janolowery** [comment]
labels complete
[Labels for cancer center marker data highlited.docx](https://github.com/colorado-cancer-center/COCancerScope/files/14103204/Labels.for.cancer.center.marker.data.highlited.docx)

**Comment by vincerubinetti** [comment]
This is great, thanks. I'll add this in right away. Let's keep the issue open until it's actually in the code.

Also what are the highlighted ones. Should we leave those as is? Should we just remove the options completely?

**Comment by janolowery** [comment]
I just forgot to un-highlight.  Please load entire list

**Comment by falquaddoomi** [comment]
From the meeting:

@janolowery will upload the most recent version of the list.

**Comment by janolowery** [comment]
Revised document with marker definitions.  Forgot to ask on call - I think we agreed to change 'Markers' to 'Resources and Facilities'.  Is this possible?
[Completed task - labels for cancer center marker data.docx](https://github.com/colorado-cancer-center/COCancerScope/files/14105172/Completed.task.-.labels.for.cancer.center.marker.data.docx)

**Comment by vincerubinetti** [comment]
I don't think we had truly settled on a term. I think "resources and facilities" probably doesn't cover all of the types of things we have there. In #29 , I changed the terminology to simply "locations". We can easily change it later if we agree on an alternative in the next meeting.

**Comment by janolowery** [comment]
Sounds good.  thanks

**Comment by vincerubinetti** [comment]
Reopening for splitting locations into categories.
