### ISSUE TITLE
Develop OpenAPI REST api that can be extended with new resources. 

### ISSUE THREAD

**Issue by seandavi** [colorado-cancer-center/COCancerScope#3]
I'm hoping that we can use the API not just for web development but also to access data. To that end, if you wanted to have an API endpoint that listed links to CSV files, that might be very user-friendly and also allow for a webpage that allows non-programmers to get access to underlying data.

**Comment by vincerubinetti** [comment]
This has been implemented by @falquaddoomi and will continue to be developed.
