### ISSUE TITLE
Specify data being presented: what part of the pop-up window is a rate?? Change pop-ups for clarifcation.

### ISSUE THREAD

**Issue by cydneyj303** [colorado-cancer-center/COCancerScope#31]
1) After selecting a county, the pop-up window pulls up too much information, and is generally confusing. What is the difference between the Value and the Age-Adj Count? Which number represents the rate? As I look through, it seems that the Value reflects the true rate, so it may be as easy as getting rid of the Age-adj Count label... Example below. 

2) We do not need to include the FIPS number anywhere; this can be removed from the pop-up. 

![count](https://github.com/colorado-cancer-center/COCancerScope/assets/139499061/0295ec41-e181-401b-9c97-6c5142495e18)

**Comment by cydneyj303** [comment]
I do like your example where we don't have a county label, so let's move forward with that! 
The number currently being presented with the "Value" label is the CORRECT number we want to display. So something like this...

**Gunnison County
Incidence (Age-adj per 100k)**: 109.5

That's all we need to include. The 17 value you have is a count (how many new cases of cancer) vs. the 109.5 is age-adjusted (taking into account the population of that county over a period of time). We only need to include the age-adjusted rate and can get rid of the count altogether. Hope this makes sense. 

Thanks!

**Comment by falquaddoomi** [comment]
Summary from meeting on tooltip for cancer stats for counties:

```
Chaffee County
Rate: 382.4
Avg. Annual Count: 121
```

For tracts, display "Census Tract <X>".

For the value field, stats that aren't cancer-related, remain "Value".

Map scale should use incidence rate ("value" internally).
