### ISSUE TITLE
Need to suppress values <5 for privacy; create new category within label specifying No Data Available

### ISSUE THREAD

**Issue by cydneyj303** [colorado-cancer-center/COCancerScope#32]
Currently, groupings of data in ECCO can start at 0. However, for privacy concerns, if there are values that are less than 5 within cancer incidence/mortality, we need to suppress this data. Example from Cancer InFocus below.

It would also be helpful to have as specific as possible the legends and groupings, instead of numbers that are rounded down/up. The picture below is an example. 

![image](https://github.com/colorado-cancer-center/COCancerScope/assets/139499061/e96e0cf8-6d7f-4dd8-b840-ea3cecca0a4c)

**Comment by vincerubinetti** [comment]
> It would also be helpful to have as specific as possible the legends and groupings, instead of numbers that are rounded down/up. 

There is already an option for this:

![image](https://github.com/colorado-cancer-center/COCancerScope/assets/8326331/e0e2bad8-e7bd-438a-bdd1-036434cd0d27)

With nice "nice steps" off, it will just divide the range between min and max evenly. With it on, it will still divide the scale evenly, but will nudge the min/max up and down and adjust the number of divisions until the numbers become "nice".

I think the latter is more readable at a glance, with less unnecessary significant digits. The option is still there to let the user specify exactly how many scale divisions to make, if they need that.

**Comment by cydneyj303** [comment]
Thank you for pointing this out! This leads to my next point...

As this will be public-facing, I think we need to limit the customizations that are available. If you can please follow through with my suggestion above; removing options for user-specifications when it comes to how the data are presented will benefit the lay community while maintaining the integrity of how the data are used/presented, which is an aim for this project. Being as specific as possible will maximize the effect of the data and platform itself. Thanks!

**Comment by cydneyj303** [comment]
> And I guess we'd only have to do this where the non-age-adjusted/absolute value is <= 5, because for age-adjusted, 3 would actually mean 300k, if I'm understanding correctly?
> 

Yes, we'd only need to do this for absolute value - though this should still be reflected for age-adjusted rates as you'd technically have no data to feed into your rate calculation (does that make sense?). Basically, if absolute value <=5, there will be "No Data" and therefore there will be "No Data" for the rate as well.

When looking at rates, a value of 3.5 would be interpreted as: "There are 3.5 breast cancer deaths for every 100,000 persons."
Absolute values are interpreted as: "There were 3 breast cancer deaths in this county." 

Age-adjusted rates are preferred in research and overall dissemination (for the most part). Hope this helps!

**Comment by vincerubinetti** [comment]
> If you can please follow through with my suggestion above

Which suggestions? Turn "nice steps" off by default? Delete all of the options on the page? If not all, which ones exactly?

**Comment by seandavi** [comment]
> Currently, groupings of data in ECCO can start at 0. However, for privacy concerns, if there are values that are less than 5 within cancer incidence/mortality, we need to suppress this data. 

The data for ECCO are currently sourced from CancerInFocus, which is, in turn, from StateCancerProfiles. They already suppress data; see https://statecancerprofiles.cancer.gov/suppressed.html. The correct number for the 5-year data (which is what our data are based on, currently) is an AAC (average annual count) of 3. **Therefore, there will never be an AAC less than three, and further suppression should not be needed.** 

Data that are suppressed are simply "missing" in the raw data. Unfortunately, I don't think there are notations about whether all missing data are suppressed data or if they are just "missing."

**Comment by cydneyj303** [comment]
Thanks Sean. Yes, the small-number rule changes depending on your data source and I do see StateCancerProfile suppresses values <3. CancerInFocus suppresses values < 5 and I'm unsure why they decided to bump that number up from 3. PHSR agrees that it's fine to have values <3 suppressed!

Either way, we still need to have a "bucket" for these values to fall into. PHSR has discussed having values < 3 categorized as "No Data Available." It would be beneficial to include a footnote or some indication that these values cannot be differentiated between "Missing", "0", and "1-3".

**Comment by vincerubinetti** [comment]
> It would be beneficial to include a footnote or some indication that these values cannot be differentiated between "Missing", "0", and "1-3".

How about:

`A 0 value may indicate truly 0, unavailable data, or a low value suppressed for privacy reasons (learn more).`, with "learn more" linking to a few sentences on the about page.

**Comment by vincerubinetti** [comment]
More discussion with Cydney today, it seems that the main issue is that with "nice steps" on, the true min/max (range) of the dataset may lie _slightly_ outside of the scale bands that are shown, e.g. scale shows steps from between 100/200/300k, but true min/max is 95/302k. I may be able to finagle the "nice steps" process, which is actually a feature of the external d3 library I'm using, to make sure the bands always "cover" the range. Perhaps I can just check if it's contained, and if not, simply add bands (keeping the same intervals) to one or both sides of the scale.
