### ISSUE TITLE
Add different tiles, change geom rendering to emphasize coloring

### ISSUE THREAD

**Issue by falquaddoomi** [colorado-cancer-center/COCancerScope#5]
During today's meeting it was brought up that the geographic features visible through the colored county/tract geometry makes it a little hard to see the color of the geoemtry. We could either add other tilemaps with less or different features, or simply make the geometry opaque as it is on the KY Cancer InFocus site.

**Comment by seandavi** [comment]
I'd be in favor of adding other tilemaps (that the user can choose) with the simplest (least features and colors) as the default. We may also want to increase opacity of the colormap. Is it a lot of work to add additional tilemaps?

**Comment by vincerubinetti** [comment]
I've added sliders for base layer (openstreetmap) and data layer (our geojson) transparency, but being able to toggle on/off certain OSM features like roads or mountains would be nice. Unfortunately, I don't think you can do this with the free OSM tile service; you'd have to host a tile server yourself, which seems like overkill for this,

Instead, I'll probably add a dropdown to change what we use as the base layer, OSM or some other tile service that for example only shows country/state borders and relief. Here's a (probably not comprehensive) list of free tile providers that are ready to hook up to Leaflet, and plenty of them look really good for varying levels of detail:

https://leaflet-extras.github.io/leaflet-providers/preview/

There's also this possibly:

https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer

**Comment by seandavi** [comment]
I like the idea of sticking with tile providers that are already plugins for Leaflet to limit complexity. The sliders add lots of flexibility as well. Thanks for doing the homework.

**Comment by vincerubinetti** [comment]
Closed by #9
